# Example of a chained workflow. (Only complete the following if the prior succeeded)
# See `workflow_run` for important note: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_run

name: Chained Workflow

# Note: This may not run on the initial branch. Chains appear to work on the main branch only.

run-name: Following up.

on:
  workflow_run:
    workflows:
      - 'Github Actions Demo'
    types:
      - completed

jobs:
  do_thing:
    name: Do the thing
    runs-on: ubuntu-latest
    steps:
      - name: Party time!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "Yay! Party time!"
      - name: Sad time!
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "Be sad now."
